version: "3.6"

services:
  almatools-tasks:
    container_name: "almatools-tasks"
    image: ghcr.io/kth-biblioteket/almatools-tasks:${REPO_TYPE}
    restart: "always"
    environment:
      TZ: ${TZ}
    env_file:
      - almatools-tasks.env
    volumes:
      - "./lastuntiltime.txt:/app/lastuntiltime.txt"
    networks:
      - "apps-net"

networks:
  apps-net:
    external: true